"use client";
import { useEffect, useState } from "react";
import { CustomerPicker } from "@/components/customer-picker";
import { EmptyState, ErrorState, LoadingState } from "@/components/data-state";
import { SecurePage } from "@/components/secure-page";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { createBankingTransaction, Customer, listCustomers, listTransactions, Transaction } from "@/services/platform";
const actions = ["Receive salary", "Deposit money", "Withdraw money", "Transfer money", "Pay merchant", "UPI payment", "Utility bill", "Subscription"];
export default function TransactionsPage() { const [customers, setCustomers] = useState<Customer[]>([]); const [customerId, setCustomerId] = useState(""); const [items, setItems] = useState<Transaction[] | null>(null); const [amount, setAmount] = useState(""); const [action, setAction] = useState(actions[0]); const [error, setError] = useState(""); const load = (id: string) => listTransactions({ customer_id: id }).then((r) => setItems(r.items)).catch(() => setError("Unable to load money movements.")); useEffect(() => { listCustomers().then((r) => { setCustomers(r.items); if (r.items[0]) { setCustomerId(r.items[0].customer_id); load(r.items[0].customer_id); } }).catch(() => setError("Unable to load your accounts.")); }, []); async function submit() { if (!customerId || !Number(amount)) return; try { await createBankingTransaction(customerId, Number(amount)); setAmount(""); load(customerId); } catch { setError("We could not record this money movement."); } } return <SecurePage title="Money" description="Move money naturally and review protected account activity."><div className="space-y-6">{error ? <ErrorState message={error}/> : !customers.length ? <LoadingState label="Loading accounts…"/> : <><CustomerPicker customers={customers} value={customerId} onChange={(id) => { setCustomerId(id); setItems(null); load(id); }}/><Card><CardHeader><CardTitle>New money movement</CardTitle><CardDescription>Record a banking operation; it is saved through the existing transaction API.</CardDescription></CardHeader><CardContent className="grid gap-3 md:grid-cols-[1fr_160px_auto]"><select className="h-11 rounded-2xl border border-border bg-background px-3 text-sm" value={action} onChange={(e) => setAction(e.target.value)}>{actions.map((item) => <option key={item}>{item}</option>)}</select><Input type="number" min="0.01" value={amount} onChange={(e) => setAmount(e.target.value)} placeholder="Amount"/><Button onClick={submit}>Confirm {action}</Button></CardContent></Card>{items === null ? <LoadingState/> : !items.length ? <EmptyState title="No money movements yet" description="Your recorded activity will appear here securely."/> : <div className="grid gap-3">{items.map((item) => <Card key={item.transaction_id} className="p-4"><div className="flex items-center justify-between gap-4"><div><p className="font-medium">Account movement</p><p className="mt-1 text-sm text-muted-foreground">{item.transaction_date} · Completed</p></div><p className="text-lg font-semibold">₹{item.transaction_amount.toLocaleString()}</p></div></Card>)}</div>}</>}</div></SecurePage>; }
