"use client";
import { ChangeEvent, useEffect, useState } from "react";
import { EmptyState, ErrorState, LoadingState } from "@/components/data-state";
import { SecurePage } from "@/components/secure-page";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { listTransactions, Transaction, uploadTransactions } from "@/services/platform";
export default function TransactionsPage() { const [items, setItems] = useState<Transaction[] | null>(null); const [customerId, setCustomerId] = useState(""); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const load = (customer = customerId) => { setItems(null); listTransactions({ customer_id: customer || undefined }).then((data) => setItems(data.items)).catch(() => setError("Unable to load transactions.")); }; useEffect(() => { load(""); }, []); async function onFile(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; setError(""); try { const result = await uploadTransactions(file); setMessage(`Imported ${result.transactions_created} transactions from ${result.rows_processed} rows.`); load(); } catch { setError("The CSV could not be imported. Confirm its required columns and try again."); } } return <SecurePage title="Transactions" description="Transaction history, filtering, upload, and persisted analytics."><div className="space-y-6"><Card><CardHeader><CardTitle>Transaction controls</CardTitle><CardDescription>Filter the history or upload a dataset using the supported CSV format.</CardDescription></CardHeader><CardContent className="flex flex-col gap-3 sm:flex-row"><Input value={customerId} onChange={(event) => setCustomerId(event.target.value)} placeholder="Customer ID"/><Button onClick={() => load()}>Apply filter</Button><Input type="file" accept=".csv" onChange={onFile}/></CardContent></Card>{message ? <p className="text-sm text-success">{message}</p> : null}{error ? <ErrorState message={error}/> : items === null ? <LoadingState/> : !items.length ? <EmptyState title="No transactions found" description="Adjust the filter or import transactions to start analyzing activity."/> : <Card><CardContent className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-muted-foreground"><tr><th className="p-3">Transaction</th><th className="p-3">Customer</th><th className="p-3">Date</th><th className="p-3">Amount</th></tr></thead><tbody>{items.map((item) => <tr key={item.transaction_id} className="border-t border-border"><td className="p-3">{item.transaction_id}</td><td className="p-3">{item.customer_id}</td><td className="p-3">{item.transaction_date}</td><td className="p-3">{item.transaction_amount.toLocaleString()}</td></tr>)}</tbody></table></CardContent></Card>}</div></SecurePage>; }
