"use client";
import { useEffect, useState } from "react";
import { CustomerPicker } from "@/components/customer-picker";
import { EmptyState, ErrorState, LoadingState } from "@/components/data-state";
import { SecurePage } from "@/components/secure-page";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Customer, getResource, listCustomers } from "@/services/platform";
const human = (text: string) => text.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
const value = (input: unknown) => typeof input === "number" ? input.toLocaleString(undefined, { maximumFractionDigits: 2 }) : String(input ?? "Not available");
export function CustomerIntelligencePage({ title, description, endpoint, emptyTitle }: { title: string; description: string; endpoint: string; emptyTitle: string }) { const [customers, setCustomers] = useState<Customer[]>([]); const [customerId, setCustomerId] = useState(""); const [data, setData] = useState<Record<string, unknown> | unknown[] | null>(null); const [error, setError] = useState(""); useEffect(() => { listCustomers().then(({ items }) => { setCustomers(items); setCustomerId(items[0]?.customer_id ?? ""); }).catch(() => setError("Unable to load accounts.")); }, []); useEffect(() => { if (!customerId) return; setData(null); getResource<Record<string, unknown> | unknown[]>(endpoint.replace(":customerId", customerId)).then(setData).catch(() => setError(`Unable to load ${title.toLowerCase()}.`)); }, [customerId, endpoint, title]); const rows = Array.isArray(data) ? data : data ? [data] : []; return <SecurePage title={title} description={description}>{error ? <ErrorState message={error}/> : !customers.length ? <EmptyState title={emptyTitle} description="Add account activity to make this intelligence available."/> : !data ? <LoadingState/> : <div className="space-y-6"><CustomerPicker customers={customers} value={customerId} onChange={setCustomerId}/>{rows.length ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{rows.flatMap((row, rowIndex) => Object.entries(row as Record<string, unknown>).filter(([, item]) => typeof item !== "object" || item === null).map(([key, item]) => <Card key={`${rowIndex}-${key}`}><CardHeader><CardTitle className="text-base">{human(key)}</CardTitle></CardHeader><CardContent><p className="text-2xl font-semibold">{value(item)}</p><CardDescription className="mt-2">Measured by the SecureWealth intelligence engine.</CardDescription></CardContent></Card>))}</div> : <EmptyState title={emptyTitle} description="The intelligence engine did not return results for this account."/>}</div>}</SecurePage>; }
