"use client";
import { useEffect, useState } from "react";
import { ArrowRight, CheckCircle2, Sparkles } from "lucide-react";
import { CustomerPicker } from "@/components/customer-picker";
import { EmptyState, ErrorState, LoadingState } from "@/components/data-state";
import { SecurePage } from "@/components/secure-page";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Customer, getResource, listCustomers } from "@/services/platform";
type Recommendation = { recommendation: string; priority: string; status: string };
const priorityClass = (priority: string) => priority.toLowerCase().includes("high") || priority.toLowerCase().includes("critical") ? "border-rose-200 bg-rose-50 text-rose-700" : priority.toLowerCase().includes("low") ? "border-slate-200 bg-slate-50 text-slate-700" : "border-amber-200 bg-amber-50 text-amber-700";
const titleFor = (text: string) => text.split(/[.!:]/)[0].slice(0, 72) || "Financial opportunity";
export default function RecommendationsPage() { const [customers, setCustomers] = useState<Customer[]>([]); const [id, setId] = useState(""); const [items, setItems] = useState<Recommendation[] | null>(null); const [error, setError] = useState(""); useEffect(() => { listCustomers().then(r => { setCustomers(r.items); setId(r.items[0]?.customer_id ?? ""); }).catch(() => setError("Unable to load accounts.")); }, []); useEffect(() => { if (!id) return; const loadRecommendations = () => getResource<Recommendation[]>(`/recommendations/${id}`).then(setItems).catch(() => setError("No runtime recommendations are available yet.")); setItems(null); void loadRecommendations(); window.addEventListener("securewealth:runtime-updated", loadRecommendations); return () => window.removeEventListener("securewealth:runtime-updated", loadRecommendations); }, [id]); return <SecurePage title="Recommendations" description="Clear next steps, ranked by your current financial situation.">{error ? <ErrorState message={error}/> : !customers.length ? <EmptyState title="No recommendations yet" description="Record activity so your financial intelligence can prepare a plan."/> : items === null ? <LoadingState label="Preparing your next best actions…"/> : <div className="space-y-6"><CustomerPicker customers={customers} value={id} onChange={setId}/>{items.length ? <section className="grid gap-5 lg:grid-cols-2">{items.map((item, index) => <Card key={`${item.recommendation}-${index}`} className="relative overflow-hidden"><CardHeader><div className="flex items-start justify-between gap-4"><div><CardDescription>Personalized recommendation</CardDescription><CardTitle className="mt-1">{titleFor(item.recommendation)}</CardTitle></div><Badge className={priorityClass(item.priority)}>{item.priority}</Badge></div></CardHeader><CardContent><div className="space-y-4 text-sm"><Block label="Why this matters" text={item.recommendation}/><Block label="Recommended action" text="Review this step and act when it fits your current cashflow."/><Block label="Expected benefit" text="Supports a stronger financial health and lower day-to-day financial risk."/><div className="flex items-center justify-between border-t pt-3"><span className="flex items-center gap-2 text-muted-foreground"><CheckCircle2 className="h-4 w-4 text-emerald-600"/>Status: {item.status}</span><span className="flex items-center gap-1 font-medium text-primary">View in Wealth Twin <ArrowRight className="h-4 w-4"/></span></div></div></CardContent></Card>)}</section> : <EmptyState title="Your plan is clear for now" description="The recommendation engine has no active actions based on your latest runtime data."/>}</div>}</SecurePage>; }
function Block({ label, text }: { label: string; text: string }) { return <div><p className="mb-1 font-medium">{label}</p><p className="text-muted-foreground">{text}</p></div>; }
