"use client";
import { FormEvent, useEffect, useState } from "react";
import { Send, Sparkles } from "lucide-react";
import { CustomerPicker } from "@/components/customer-picker";
import { EmptyState, ErrorState, LoadingState } from "@/components/data-state";
import { SecurePage } from "@/components/secure-page";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Customer, getResource, listCustomers } from "@/services/platform";
type Decision = { final_decision?: string; confidence_score?: number; reasoning_chain?: string; supporting_evidence?: string; recommended_actions?: string };
const prompts = ["Summarize my finances", "Why did my fraud score change?", "Explain my Wealth Score", "Can I afford a loan?"];
export default function AgenticAiPage() { const [customers, setCustomers] = useState<Customer[]>([]); const [id, setId] = useState(""); const [decision, setDecision] = useState<Decision>(); const [text, setText] = useState(""); const [messages, setMessages] = useState<{ role: "user" | "assistant"; text: string }[]>([]); const [error, setError] = useState(""); useEffect(() => { listCustomers().then(r => { setCustomers(r.items); setId(r.items[0]?.customer_id ?? ""); }).catch(() => setError("Unable to load accounts.")); }, []); useEffect(() => { if (!id) return; getResource<Decision>(`/agentic-ai/${id}`).then(d => { setDecision(d); setMessages([{ role: "assistant", text: d.final_decision ?? "Your financial decision context is ready." }]); }).catch(() => setError("No runtime agent decision is available yet. Record a transaction to activate your Wealth Twin.")); }, [id]); function send(event?: FormEvent, prompt = text) { event?.preventDefault(); if (!prompt.trim() || !decision) return; const evidence = decision.supporting_evidence ? ` Evidence: ${decision.supporting_evidence}.` : ""; const answer = `${decision.final_decision ?? "Decision context is available."} Confidence: ${Math.round((decision.confidence_score ?? 0) * 100)}%. ${decision.recommended_actions ? `Suggested action: ${decision.recommended_actions}.` : ""}${evidence}`; setMessages(m => [...m, { role: "user", text: prompt }, { role: "assistant", text: answer }]); setText(""); } return <SecurePage title="SecureWealth Twin" description="Your conversational decision assistant, grounded in persisted runtime intelligence.">{error ? <ErrorState message={error}/> : !customers.length ? <EmptyState title="No Wealth Twin yet" description="Connect an account and record activity to activate it."/> : !decision ? <LoadingState/> : <div className="space-y-5"><CustomerPicker customers={customers} value={id} onChange={setId}/><Card><CardHeader><CardTitle className="flex items-center gap-2"><Sparkles className="text-primary"/>Your Wealth Twin</CardTitle><CardDescription>Answers are constrained to Fraud, Behaviour, Wealth Twin, recommendations, and runtime decision evidence.</CardDescription></CardHeader><CardContent className="space-y-4">{messages.map((m, i) => <div key={i} className={`max-w-3xl rounded-2xl p-4 text-sm ${m.role === "assistant" ? "bg-muted" : "ml-auto bg-primary text-primary-foreground"}`}>{m.text}</div>)}<div className="flex flex-wrap gap-2">{prompts.map(p => <Button key={p} variant="outline" size="sm" onClick={() => send(undefined, p)}>{p}</Button>)}</div><form onSubmit={send} className="flex gap-2"><Input value={text} onChange={e => setText(e.target.value)} placeholder="Ask about a transfer, loan, fraud score, or your finances…"/><Button type="submit"><Send className="h-4 w-4"/></Button></form></CardContent></Card></div>}</SecurePage>; }
