from __future__ import annotations

import json
import logging
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import pandas as pd

from ml.agentic_ai.confidence_scorer import DecisionConfidenceScorer
from ml.agentic_ai.context_builder import UnifiedCustomerContextBuilder
from ml.agentic_ai.fraud_escalation import FraudEscalationPolicy
from ml.agentic_ai.priority_engine import AgenticPriorityEngine
from ml.agentic_ai.reasoning_engine import ExplainableReasoningEngine
from ml.agentic_ai.recommendation_resolver import RecommendationConflictResolver

LOGGER = logging.getLogger(__name__)


@dataclass(frozen=True)
class AgenticAIDecisionResult:
    """Persisted final decisions generated by the Agentic AI Decision Engine."""

    decisions: pd.DataFrame
    customer_count: int
    escalated_count: int
    output_directory: Path


class AgenticAIDecisionEngine:
    """Coordinate intelligence layers into safe, explainable final customer decisions."""

    def __init__(self) -> None:
        self.context_builder = UnifiedCustomerContextBuilder()
        self.fraud_escalation_policy = FraudEscalationPolicy()
        self.recommendation_resolver = RecommendationConflictResolver()
        self.priority_engine = AgenticPriorityEngine()
        self.confidence_scorer = DecisionConfidenceScorer()
        self.reasoning_engine = ExplainableReasoningEngine()

    def build(
        self,
        customer_features: pd.DataFrame,
        behavioral_features: pd.DataFrame,
        fraud_scores: pd.DataFrame,
        wealth_twins: pd.DataFrame,
        financial_recommendations: pd.DataFrame,
        output_dir: str | Path,
    ) -> AgenticAIDecisionResult:
        """Generate one final decision per customer and persist Sprint 4C artifacts."""
        context = self.context_builder.build(
            customer_features,
            behavioral_features,
            fraud_scores,
            wealth_twins,
            financial_recommendations,
        )
        timestamp = datetime.now(timezone.utc).isoformat()
        records = [self._build_decision(customer, timestamp) for _, customer in context.iterrows()]
        decisions = pd.DataFrame(records)

        output_path = Path(output_dir)
        output_path.mkdir(parents=True, exist_ok=True)
        decisions.to_parquet(output_path / "agentic_ai_decisions.parquet", index=False)
        escalated_count = int(decisions["risk_summary"].map(lambda value: json.loads(value)["escalated"]).sum())
        with (output_path / "agentic_ai_metadata.json").open("w", encoding="utf-8") as file_handle:
            json.dump(
                {
                    "artifact": "agentic_ai_decisions.parquet",
                    "customer_count": int(context["customer_id"].nunique()),
                    "escalated_decision_count": escalated_count,
                    "required_decision_fields": [
                        "customer_id", "final_decision", "decision_priority", "confidence_score", "reasoning_chain",
                        "supporting_evidence", "recommended_actions", "risk_summary", "financial_summary", "timestamp",
                    ],
                    "input_sources": [
                        "customer_behaviour", "behavioral_intelligence", "fraud_intelligence", "digital_wealth_twin",
                        "financial_decision_intelligence",
                    ],
                },
                file_handle,
                indent=2,
                sort_keys=True,
            )
        LOGGER.info("Generated %s agentic decisions; %s require fraud escalation", len(decisions), escalated_count)
        return AgenticAIDecisionResult(decisions, int(context["customer_id"].nunique()), escalated_count, output_path)

    def _build_decision(self, customer: pd.Series, timestamp: str) -> dict[str, object]:
        escalation = self.fraud_escalation_policy.evaluate(customer)
        recommendations = customer.get("agentic_recommendations", [])
        if not isinstance(recommendations, list):
            recommendations = []
        actions = self.recommendation_resolver.resolve(recommendations, bool(escalation["escalated"]))
        recommended_actions = list(escalation["actions"]) + [str(action["recommendation"]) for action in actions]
        priority = self.priority_engine.determine(str(escalation["priority"]), actions)
        confidence = self.confidence_scorer.score(
            customer,
            [float(action["confidence_score"]) for action in actions],
            float(escalation["confidence"]),
        )
        return {
            "customer_id": str(customer["customer_id"]),
            "final_decision": str(escalation["final_decision"]),
            "decision_priority": priority,
            "confidence_score": confidence,
            "reasoning_chain": json.dumps(self.reasoning_engine.build_reasoning_chain(customer, escalation, actions)),
            "supporting_evidence": json.dumps(self.reasoning_engine.supporting_evidence(customer), sort_keys=True),
            "recommended_actions": json.dumps(recommended_actions),
            "risk_summary": json.dumps(self.reasoning_engine.risk_summary(customer, escalation), sort_keys=True),
            "financial_summary": json.dumps(self.reasoning_engine.financial_summary(customer), sort_keys=True),
            "timestamp": timestamp,
        }
