"use client";
import { useEffect, useState } from "react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { CustomerPicker } from "@/components/customer-picker";
import { EmptyState, ErrorState, LoadingState } from "@/components/data-state";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { getResource, listCustomers, listTransactions, Customer } from "@/services/platform";

const label = (value: unknown) => value === null || value === undefined ? "—" : typeof value === "number" ? value.toLocaleString(undefined, { maximumFractionDigits: 2 }) : String(value);

export default function DashboardPage() {
  const [customers, setCustomers] = useState<Customer[]>([]); const [customerId, setCustomerId] = useState(""); const [dashboard, setDashboard] = useState<Record<string, any> | null>(null); const [transactions, setTransactions] = useState<any[]>([]); const [error, setError] = useState("");
  useEffect(() => { listCustomers().then(({ items }) => { setCustomers(items); setCustomerId(items[0]?.customer_id ?? ""); }).catch(() => setError("Unable to load customer data.")); }, []);
  useEffect(() => { if (!customerId) return; setDashboard(null); Promise.all([getResource<Record<string, any>>(`/dashboard/${customerId}`), listTransactions({ customer_id: customerId })]).then(([data, transactionPage]) => { setDashboard(data); setTransactions(transactionPage.items); }).catch(() => setError("Unable to load the selected customer dashboard.")); }, [customerId]);
  if (error) return <ErrorState message={error} />;
  if (!customers.length) return <EmptyState title="No customer data available" description="Import transactions or create a customer to populate the financial intelligence workspace." />;
  if (!dashboard) return <LoadingState label="Loading financial intelligence…" />;
  const cards = dashboard.cards ?? {}; const recommendations = dashboard.recommendations ?? []; const spending = Object.entries(dashboard.charts?.spending ?? {}).filter(([, value]) => typeof value === "number").slice(0, 8).map(([key, value]) => ({ key: key.replaceAll("_", " "), value }));
  return <div className="space-y-8 pb-8"><CustomerPicker customers={customers} value={customerId} onChange={setCustomerId} /><section className="grid gap-4 xl:grid-cols-4">{Object.entries(cards).map(([key, value]) => <Card key={key}><CardHeader><CardTitle className="text-base font-medium text-muted-foreground">{key.replaceAll("_", " ")}</CardTitle><p className="text-3xl font-semibold tracking-tight">{label(value)}</p></CardHeader></Card>)}</section><section className="grid gap-6 lg:grid-cols-[1.4fr_0.8fr]"><Card><CardHeader><CardTitle>Customer activity</CardTitle><CardDescription>Live behavioral intelligence measures for the selected customer.</CardDescription></CardHeader><CardContent className="h-72">{spending.length ? <ResponsiveContainer width="100%" height="100%"><AreaChart data={spending}><CartesianGrid strokeDasharray="3 3" strokeOpacity={0.15}/><XAxis dataKey="key" hide/><YAxis/><Tooltip/><Area type="monotone" dataKey="value" stroke="hsl(var(--primary))" fill="hsl(var(--primary) / 0.2)"/></AreaChart></ResponsiveContainer> : <p className="text-sm text-muted-foreground">No numeric behavior measures are available.</p>}</CardContent></Card><Card><CardHeader><CardTitle>Recent transactions</CardTitle><CardDescription>Data persisted in the transaction service.</CardDescription></CardHeader><CardContent>{transactions.length ? transactions.slice(0, 5).map((transaction) => <div key={transaction.transaction_id} className="flex items-center justify-between border-b border-border py-3 text-sm"><span>{transaction.transaction_id}</span><span>{label(transaction.transaction_amount)}</span></div>) : <p className="text-sm text-muted-foreground">No transactions for this customer.</p>}</CardContent></Card></section><section className="grid gap-6 lg:grid-cols-2"><Card><CardHeader><CardTitle>Fraud posture</CardTitle><CardDescription>Risk score and flagged transaction summary.</CardDescription></CardHeader><CardContent><Badge>{label(dashboard.kpis?.fraud?.average_fraud_score)} average score</Badge><p className="mt-4 text-sm text-muted-foreground">{label(dashboard.kpis?.fraud?.flagged_transactions)} flagged across {label(dashboard.kpis?.fraud?.transactions_analyzed)} analyzed transactions.</p></CardContent></Card><Card><CardHeader><CardTitle>AI recommendations</CardTitle><CardDescription>Ranked actions from Financial Decision Intelligence.</CardDescription></CardHeader><CardContent>{recommendations.length ? recommendations.slice(0, 3).map((item: Record<string, any>, index: number) => <div key={index} className="rounded-2xl border border-border bg-muted/40 p-4 text-sm">{item.recommendation ?? item.explanation ?? JSON.stringify(item)}</div>) : <p className="text-sm text-muted-foreground">No recommendations available.</p>}</CardContent></Card></section></div>;
}
