"use client";
import { useEffect, useState } from "react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { CustomerPicker } from "@/components/customer-picker";
import { EmptyState, ErrorState, LoadingState } from "@/components/data-state";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { getResource, listCustomers, listTransactions, Customer } from "@/services/platform";

const label = (value: unknown) => value === null || value === undefined ? "—" : typeof value === "number" ? value.toLocaleString(undefined, { maximumFractionDigits: 2 }) : String(value);

export default function DashboardPage() {
  const [customers, setCustomers] = useState<Customer[] | null>(null); const [customerId, setCustomerId] = useState(""); const [dashboard, setDashboard] = useState<Record<string, any> | null>(null); const [transactions, setTransactions] = useState<any[]>([]); const [error, setError] = useState("");
  const loadAccounts = () => { setError(""); listCustomers().then(({ items }) => { setCustomers(items); setCustomerId(items[0]?.customer_id ?? ""); }).catch(() => setError("Unable to contact the banking service. Please try again.")); };
  useEffect(() => { loadAccounts(); }, []);
  useEffect(() => { if (!customerId) return; setDashboard(null); Promise.all([getResource<Record<string, any>>(`/dashboard/${customerId}`), listTransactions({ customer_id: customerId })]).then(([data, transactionPage]) => { setDashboard(data); setTransactions(transactionPage.items); }).catch(() => setError("Unable to load the selected customer dashboard.")); }, [customerId]);
  if (error) return <ErrorState message={error} onRetry={loadAccounts} />;
  if (customers === null) return <LoadingState />;
  if (!customers.length) return <EmptyState title="Welcome to SecureWealth" description="Create your first account, make a money movement, and our financial guardian will begin monitoring your financial health." />;
  if (!dashboard) return <LoadingState label="Preparing your financial overview…" />;
  const cards = dashboard.cards ?? {}; const recommendations = dashboard.recommendations ?? []; const spending = Object.entries(dashboard.charts?.spending ?? {}).filter(([, value]) => typeof value === "number").slice(0, 8).map(([key, value]) => ({ key: key.replaceAll("_", " "), value }));
  return <div className="space-y-8 pb-8"><CustomerPicker customers={customers} value={customerId} onChange={setCustomerId} /><section className="grid gap-4 xl:grid-cols-4">{Object.entries(cards).map(([key, value]) => <Card key={key}><CardHeader><CardTitle className="text-base font-medium text-muted-foreground">{key.replaceAll("_", " ")}</CardTitle><p className="text-3xl font-semibold tracking-tight">{label(value)}</p></CardHeader></Card>)}</section><section className="grid gap-6 lg:grid-cols-[1.4fr_0.8fr]"><Card><CardHeader><CardTitle>Financial activity</CardTitle><CardDescription>Your account behaviour, interpreted by SecureWealth.</CardDescription></CardHeader><CardContent className="h-72">{spending.length ? <ResponsiveContainer width="100%" height="100%"><AreaChart data={spending}><CartesianGrid strokeDasharray="3 3" strokeOpacity={0.15}/><XAxis dataKey="key" hide/><YAxis/><Tooltip/><Area type="monotone" dataKey="value" stroke="hsl(var(--primary))" fill="hsl(var(--primary) / 0.2)"/></AreaChart></ResponsiveContainer> : <p className="text-sm text-muted-foreground">Your insights are being prepared.</p>}</CardContent></Card><Card><CardHeader><CardTitle>Recent activity</CardTitle><CardDescription>Your latest money movements.</CardDescription></CardHeader><CardContent>{transactions.length ? transactions.slice(0, 5).map((transaction) => <div key={transaction.transaction_id} className="flex items-center justify-between border-b border-border py-3 text-sm"><span>Account movement · {transaction.transaction_date}</span><span>₹{label(transaction.transaction_amount)}</span></div>) : <p className="text-sm text-muted-foreground">No activity yet. Start with a deposit or payment.</p>}</CardContent></Card></section><section className="grid gap-6 lg:grid-cols-2"><Card><CardHeader><CardTitle>Security monitoring</CardTitle><CardDescription>Protection status from fraud intelligence.</CardDescription></CardHeader><CardContent><Badge>{label(dashboard.kpis?.fraud?.average_fraud_score)} risk score</Badge><p className="mt-4 text-sm text-muted-foreground">{label(dashboard.kpis?.fraud?.flagged_transactions)} unusual movements across {label(dashboard.kpis?.fraud?.transactions_analyzed)} analyzed.</p></CardContent></Card><Card><CardHeader><CardTitle>Recommended next steps</CardTitle><CardDescription>Personalized actions from your financial intelligence.</CardDescription></CardHeader><CardContent>{recommendations.length ? recommendations.slice(0, 3).map((item: Record<string, any>, index: number) => <div key={index} className="rounded-2xl border border-border bg-muted/40 p-4 text-sm">{item.recommendation ?? item.explanation ?? "Personalized guidance is ready in Recommendations."}</div>) : <p className="text-sm text-muted-foreground">Recommendations are being prepared.</p>}</CardContent></Card></section></div>;
}
